### PR TITLE
Update JS for django admin, add support for Grappelli

### PR DESCRIPTION
**Pull request by blueyed**
This adopts the API changes for Parsley 2 and adds support for
django-grappelli, which uses different row classes.

Ref: https://github.com/sehmaschine/django-grappelli/issues/494

### CODE REVIEW

**Comment by mauricioabreu** [comment]
This PR is kinda old. :(
Is it still valid?

**Comment by blueyed** [comment]
Yes, I think so.

**Comment by shivakrshn49** [comment]
@blueyed Admin form validation was not working in this pull request

**Comment by akshar-raaj** [comment]
@blueyed Made some changes in parsley.django-admin.js as per https://github.com/agiliq/Django-parsley/commit/62e58c9c4b6bd62388976e3140c0023552990284

Can you update your PR if required? If you think it doesn't need any changes even though I have made changes in parsley.django-admin.js, then let me know and we can look into your PR.

**Comment by blueyed** [comment]
@burumbot (and others)
Please consider picking it up, and creating a new PR from it.
Not sure if it would get accepted though (in a timely manner).

**Comment by blueyed** [comment]
Or maybe it can get accepted from here still?! (not sure if there are conflicts)
(I am not using it myself currently anymore.)

**Pull request closed without merging**
